CREATE TABLE IF NOT EXISTS public.species_logins (
    id          BIGSERIAL PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
    aid         TEXT        NOT NULL,
    species     TEXT        NOT NULL,
    event_type  TEXT        NOT NULL DEFAULT 'PlayerRespawn'
);

CREATE TABLE IF NOT EXISTS public.species_diets (
    species  TEXT PRIMARY KEY,
    diet     TEXT NOT NULL CHECK (diet IN ('carnivore', 'herbivore', 'omnivore'))
);

INSERT INTO public.species_diets (species, diet) VALUES
    ('Achillobator',                'carnivore'),
    ('Acrocanthosaurus',            'carnivore'),
    ('Aerosteon',                   'carnivore'),
    ('Alioramus',                   'carnivore'),
    ('Allosaurus',                  'carnivore'),
    ('Allosaurus (Exa)',            'carnivore'),
    ('Andrewsarchus',               'carnivore'),
    ('Ankylorhiza',                 'carnivore'),
    ('Archelon',                    'carnivore'),
    ('Asylum Felinae',              'carnivore'),
    ('Asylum Wolf',                 'carnivore'),
    ('Australovenator',             'carnivore'),
    ('Austroraptor',                'carnivore'),
    ('Bistahieversor',              'carnivore'),
    ('Bonapartenykus',              'carnivore'),
    ('Carcharodontosaurus',         'carnivore'),
    ('Carnotaurus',                 'carnivore'),
    ('Ceratosaurus',                'carnivore'),
    ('Citipati',                    'carnivore'),
    ('Compsognathus',               'carnivore'),
    ('Concavenator',                'carnivore'),
    ('Cougar',                      'carnivore'),
    ('Cryolophosaurus',             'carnivore'),
    ('Daspletosaurus',              'carnivore'),
    ('Deinonychus',                 'carnivore'),
    ('Deinosuchus',                 'carnivore'),
    ('Deltadromeus',                'carnivore'),
    ('Dilophosaurus',               'carnivore'),
    ('Dimetrodon',                  'carnivore'),
    ('Dimetrodon Grandis',          'carnivore'),
    ('Dimetrodon Milleri',          'carnivore'),
    ('Diplocaulus',                 'carnivore'),
    ('Dryptosaurus',                'carnivore'),
    ('Dunkleosteus',                'carnivore'),
    ('Ekrixinatosaurus',            'carnivore'),
    ('Eurhinosaurus',               'carnivore'),
    ('Giant Salamander',            'carnivore'),
    ('Giganotosaurus',              'carnivore'),
    ('Gigarachne',                  'carnivore'),
    ('Griffin',                     'carnivore'),
    ('Halszkaraptor',               'carnivore'),
    ('Hatzegopteryx',               'carnivore'),
    ('Helicoprion',                 'carnivore'),
    ('Hibbertopterus',              'carnivore'),
    ('Ichtyovenator',               'carnivore'),
    ('Inostrancevia',               'carnivore'),
    ('Kaiwhekea',                   'carnivore'),
    ('Kaprosuchus',                 'carnivore'),
    ('Kelenken',                    'carnivore'),
    ('Kryptops',                    'carnivore'),
    ('Latenivenatrix',              'carnivore'),
    ('Livyatan',                    'carnivore'),
    ('Maip',                        'carnivore'),
    ('Megalania',                   'carnivore'),
    ('Metriacanthosaurus',          'carnivore'),
    ('Microraptor',                 'carnivore'),
    ('Mosasaurus',                  'carnivore'),
    ('Nanuqsaurus',                 'carnivore'),
    ('Nyctatyrannus',               'carnivore'),
    ('Orcinus Orca',                'carnivore'),
    ('Poposaurus',                  'carnivore'),
    ('Prognathodon',                'carnivore'),
    ('Pycnonemosaurus',             'carnivore'),
    ('Quetzalcoatlus',              'carnivore'),
    ('Rhamphorynchus',              'carnivore'),
    ('Sachicasaurus',               'carnivore'),
    ('Sarcosuchus',                 'carnivore'),
    ('Saurophaganax',               'carnivore'),
    ('Shonisaurus',                 'carnivore'),
    ('Smilodon',                    'carnivore'),
    ('Spinosaurus',                 'carnivore'),
    ('Squalicorax',                 'carnivore'),
    ('Suchomimus',                  'carnivore'),
    ('Thalassodromeus',             'carnivore'),
    ('Titanoboa',                   'carnivore'),
    ('Torvosaurus',                 'carnivore'),
    ('Tropeognathus',               'carnivore'),
    ('Tylosaurus',                  'carnivore'),
    ('Tyrannosaurus',               'carnivore'),
    ('Tyrannosaurus (PT)',          'carnivore'),
    ('Tyrannotitan',                'carnivore'),
    ('Utahraptor',                  'carnivore'),
    ('Utahraptor (Rework)',         'carnivore'),
    ('Velocciraptor',               'carnivore'),
    ('Xiphactinus',                 'carnivore'),
    ('Yutyrannus',                  'carnivore'),
    ('Zhuchengtyrannus',            'carnivore'),
    ('Albertaceratops',             'herbivore'),
    ('Amargasaurus',                'herbivore'),
    ('Ampelosaurus',                'herbivore'),
    ('Anodontosaurus',              'herbivore'),
    ('Apatosaurus',                 'herbivore'),
    ('Argentinosaurus',             'herbivore'),
    ('Asylum Deer',                 'herbivore'),
    ('Barsboldia',                  'herbivore'),
    ('Brachiosaurus',               'herbivore'),
    ('Camarasaurus (Agc)',          'herbivore'),
    ('Camptosaurus',                'herbivore'),
    ('Chaostriceratops',            'herbivore'),
    ('Deinocheirus',                'herbivore'),
    ('Desmatosuchus',               'herbivore'),
    ('Dryosaurus',                  'herbivore'),
    ('Edmontosaurus Annectens',     'herbivore'),
    ('Edmontosaurus Regalis',       'herbivore'),
    ('Eotriceratops',               'herbivore'),
    ('Eotriceratops (Pb)',          'herbivore'),
    ('Euphelopus',                  'herbivore'),
    ('Gigantoraptor',               'herbivore'),
    ('Iguanodon',                   'herbivore'),
    ('Kentrosaurus',                'herbivore'),
    ('Lambeosaurus',                'herbivore'),
    ('Leedsichthys',                'herbivore'),
    ('Lisowicia',                   'herbivore'),
    ('Lurdusaurus',                 'herbivore'),
    ('Mammuthus Columbi',           'herbivore'),
    ('Miragaia',                    'herbivore'),
    ('Muttaburrasaurus',            'herbivore'),
    ('Nasutoceratops',              'herbivore'),
    ('Ocepechelon',                 'herbivore'),
    ('Pachycephalosaurus',          'herbivore'),
    ('Pachycephalosaurus (Beaked)', 'herbivore'),
    ('Pachyrhinosaurus',            'herbivore'),
    ('Paraceratherium',             'herbivore'),
    ('Parasaurolophus',             'herbivore'),
    ('Peloroplites',                'herbivore'),
    ('Pentaceratops',               'herbivore'),
    ('Psittacosaurus',              'herbivore'),
    ('Stegosaurus',                 'herbivore'),
    ('Struthiomimus',               'herbivore'),
    ('Styracosaurus',               'herbivore'),
    ('Suzhousaurus',                'herbivore'),
    ('Tenontosaurus',               'herbivore'),
    ('Therizinosaurus',             'herbivore'),
    ('Yunnanosaurus',               'herbivore'),
    ('Bristlewing',                 'carnivore'),
    ('Bwi',                         'herbivore'),
    ('Cerataspida',                 'carnivore'),
    ('Dankanaptera',                'carnivore'),
    ('Dominus',                     'carnivore'),
    ('Dracoviper',                  'carnivore'),
    ('Gigamandra',                  'carnivore'),
    ('Glowplume',                   'herbivore'),
    ('Golugore',                    'carnivore'),
    ('Gonaria',                     'herbivore'),
    ('Hannek',                      'herbivore'),
    ('Hebu-Bebu',                   'herbivore'),
    ('Madrehorn',                   'herbivore'),
    ('Magna Ant',                   'carnivore'),
    ('Moraquile',                   'carnivore'),
    ('Noviana',                     'herbivore'),
    ('Ophis',                       'carnivore'),
    ('Platyhystrix',                'carnivore'),
    ('Susecdurus',                  'carnivore'),
    ('Thalasrex',                   'carnivore')
ON CONFLICT (species) DO NOTHING;
